print('init.lua ver 1.2')
ip = wifi.sta.getip()
print(ip)
wifi.setmode(wifi.STATION)
wifi.sta.config("esptest","Tp-l4113")
ip = wifi.sta.getip()
print(ip)
print('set mode=STATION (mode='..wifi.getmode()..')')
print('MAC: ',wifi.sta.getmac())
print('chip: ',node.chipid())
print('heap: ',node.heap())
dofile('telnet.lua')

